<?php
/**
 * @file 
 *
 */

module_load_include('inc', 'd2d_server', 'includes/db');
module_load_include('inc', 'd2d_server', 'includes/theme');

/**
 * Implements hook_entity_info().
 */
function d2d_server_entity_info() {
  $return['d2d_entity'] = array(
    'label' => t('D2D Server'),
    'base table' => 'd2d_entity',
    'entity keys' => array(
      'id' => 'did',
      'label' => 'title',
    ),
    'entity class' => 'D2DEntity',
    'uri callback' => 'entity_class_uri',
    'controller class' => 'D2DEntityController',
    'admin ui' => array(
      'path' => 'admin/d2d_server',
      'controller class' => 'D2DEntityUIController',
      'file' => 'includes/d2d_entity.admin.inc',
    ),
    'module' => 'd2d_server',
    'access callback' => 'd2d_server_admin_access',
    'fieldable' => TRUE,
    'bundles' => array(
      'd2d_entity' => array(
        'label' => t('d2d entity bundle'),
        'admin' => array(
          'path' => 'admin/d2d_server',
          'access arguments' => array('administer d2d server'),
        ),
      ),
    ),
  );

  return $return;
}

/**
 * accesss callback function for hook_entity_info().
 */
function d2d_server_admin_access($op, $profile = NULL, $account = NULL) {
  if (user_access('administer d2d server', $account)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_permission().
 */
function d2d_server_permission() {
  return array(
    'administer d2d server' => array(
      'title' => t('Administer Patterns Server'),
    ),
    'view d2d server' => array(
      'title' => t('View Patterns Server list and page'),
    ),
  );
}

/**
 */
function d2d_server_menu() {
  $items = array();

  //main page.
  //use the $property pid of _patterns_server_list().
  $items['d2d_server_homepage'] = array(
    'title' => 'List of all d2d instances',
    'description' => 'the list of all d2d instances',
    'page callback' => '_d2d_server_all_list_page',
    'page arguments' => array(),
    'access arguments' => array('view d2d server'),
  );

  //d2d instance's view page. "d2d/$did"
  //if success, go to d2d/$did page.
  //if not(the $pid is wrong), go to the main page.
  $items['d2d/%'] = array(
    'title' => 'd2d instance view',
    'description' => 'd2d instance view page',
    'page callback' => '_d2d_instance_view_page',
    'page arguments' => array(1),
    'access arguments' => array('view d2d server'),
  );

  $items['d2d/category/%'] = array(
    'title' => 'all d2d instances in % category',
    'description' => 'all d2d instances in % category',
    'page callback' => '_d2d_server_list_basicpage',
    'page arguments' => array(1, 2),
    'access arguments' => array('view d2d server'),
  );

  $items['d2d/tags/%/%'] = array(
    'title' => 'all d2d instances with the tag %',
    'description' => 'all d2d instances with the tag %',
    'page callback' => '_d2d_server_list_basicpage',
    'page arguments' => array(2, 3),
    'access arguments' => array('view d2d server'),
  );

  //this is search function. search text & search type.
  //actually its result is composed by the above four basic kinds of table.
  $items['d2d/search/%/%'] = array(
    'title' => 'search d2d instances',
    'description' => 'search d2d instances with value/category, and so on',
    'page callback' => '_d2d_server_search',
    'page arguments' => array(2, 3),
    'access arguments' => array('view d2d server'),
  );

  return $items;
}

function _d2d_server_all_list_page() {
  $entity = field_info_instances('d2d_entity', 'd2d_entity');
  foreach ($entity as $key => $value) {
    $p = field_info_field($key);
    dsm($p);
  }
  dsm($entity);
  return "hello world!";
}

function _d2d_instance_view_page($did) {
  $de = entity_object_load($did, 'd2d_entity');
  if (!$de) {
    drupal_set_message(t("The d2d instance doesn't exist.", "error"));
    drupal_goto('d2d_server_homepage');
  }
  drupal_set_title($de->title);
  $fieldset_title = $de->title;

  //drupal_add_css(drupal_get_path('module', 'patterns_server') . '/styles/css/patterns_server.viewpage.css');
  //drupal_add_js(drupal_get_path('module', 'patterns_server') . '/styles/js/patterns_server.viewpage.js');

  //$backtoserver_voting_link = _patterns_server_back_like_button($pid);
  $content = "<div id='one_pattern_div'><fieldset><legend>$fieldset_title</legend><div class='fieldset-wrapper'>";
  //$content = "<div id='one_pattern_div'><fieldset><legend>$fieldset_title$backtoserver_voting_link</legend><div class='fieldset-wrapper'>";

  $content .= _d2d_instance_view_page_description($de);

  $content .= '</div></fieldset></div>';
  $field_view = entity_view('d2d_entity', array($did => $de));
  $content .= drupal_render($field_view);

  return $content;

}


function _d2d_server_list_basicpage($type, $value) {
}

function _d2d_server_search($type, $value) {
}
