<?php
/**
 * @file 
 *
 */

module_load_include('inc', 'd2d_server', 'includes/db');

/**
 * Implements hook_entity_info().
 */
function d2d_server_entity_info() {
  $return['d2d_entity'] = array(
    'label' => t('D2D Server'),
    'base table' => 'd2d_entity',
    'entity keys' => array(
      'id' => 'did',
      'label' => 'title',
    ),
    'entity class' => 'D2DEntity',
    'uri callback' => 'entity_class_uri',
    'controller class' => 'D2DEntityController',
    'admin ui' => array(
      'path' => 'admin/d2d_server',
      'controller class' => 'D2DEntityUIController',
      'file' => 'includes/d2d_entity.admin.inc',
    ),
    'module' => 'd2d_server',
    'access callback' => 'd2d_server_admin_access',
    'fieldable' => TRUE,
    'bundles' => array(
      'd2d_entity' => array(
        'label' => t('d2d entity bundle'),
        'admin' => array(
          'path' => 'admin/d2d_server',
          'access arguments' => array('administer d2d server'),
        ),
      ),
    ),
  );

  return $return;
}

/**
 * accesss callback function for hook_entity_info().
 */
function d2d_server_admin_access($op, $profile = NULL, $account = NULL) {
  if (user_access('administer d2d server', $account)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_permission().
 */
function d2d_server_permission() {
  return array(
    'administer d2d server' => array(
      'title' => t('Administer Patterns Server'),
    ),
    'view d2d server' => array(
      'title' => t('View Patterns Server list and page'),
    ),
  );
}

/**
 */
function d2d_server_menu() {
  $items = array();

  //main page.
  //use the $property pid of _patterns_server_list().
  $items['d2d_server_homepage'] = array(
    'title' => 'List of all d2d instances',
    'description' => 'the list of all d2d instances',
    'page callback' => '_d2d_server_all_list_page',
    'page arguments' => array(),
    'access arguments' => array('view d2d server'),
  );

  return $items;
}

function _d2d_server_all_list_page() {
  $entity = field_info_instances('d2d_entity', 'd2d_entity');
  foreach ($entity as $key => $value) {
    $p = field_info_field($key);
    dsm($p);
  }
  dsm($entity);
  return "hello world!";
}
